In [1]:
import pandas as pd
import os

In [2]:


base_path = "00. Data"

arquivos = [
    "olist_customers_dataset.csv",
    "olist_geolocation_dataset.csv",
    "olist_order_items_dataset.csv",
    "olist_order_payments_dataset.csv",
    "olist_order_reviews_dataset.csv",
    "olist_orders_dataset.csv",
    "olist_products_dataset.csv",
    "olist_sellers_dataset.csv",
    "product_category_name_translation.csv"
]

dfs = {}

for arquivo in arquivos:
    nome_df =  arquivo.replace(".csv", "")
    path = os.path.join(base_path, arquivo)
    dfs[nome_df] = pd.read_csv(path)

# df_customers = dfs["olist_customers_dataset"]
# df_geolocation =   dfs["olist_customers_dataset"]

In [3]:
dfs.keys()

dict_keys(['olist_customers_dataset', 'olist_geolocation_dataset', 'olist_order_items_dataset', 'olist_order_payments_dataset', 'olist_order_reviews_dataset', 'olist_orders_dataset', 'olist_products_dataset', 'olist_sellers_dataset', 'product_category_name_translation'])

In [4]:
#dfs["olist_customers_dataset"]

In [5]:
dfs["olist_order_items_dataset"]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [6]:
dfs["olist_order_items_dataset"]['product_id'].value_counts()

product_id
aca2eb7d00ea1a7b8ebd4e68314663af    527
99a4788cb24856965c36a24e339b6058    488
422879e10f46682990de24d770e7f83d    484
389d119b48cf3043d311335e499d9c6b    392
368c6c730842d78016ad823897a372db    388
                                   ...
4cc4d02efc8f249c13355147fb44e34d      1
b10ecf8e33aaaea419a9fa860ea80fb5      1
dd469c03ad67e201bc2179ef077dcd48      1
bbe7651fef80287a816ead73f065fc4b      1
350688d9dc1e75ff97be326363655e01      1
Name: count, Length: 32951, dtype: int64

In [7]:
dfs["olist_products_dataset"]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [8]:
df_1 = pd.merge(dfs["olist_order_items_dataset"], dfs["olist_products_dataset"][['product_id','product_category_name']],on='product_id', how='left')
df_1

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,cool_stuff
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,pet_shop
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,moveis_decoracao
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,perfumaria
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,ferramentas_jardim
...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,utilidades_domesticas
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,informatica_acessorios
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,esporte_lazer
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,informatica_acessorios
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,cama_mesa_banho

In [9]:
df_1[df_1['order_item_id']>1]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name
14,0008288aa423d2a3f00fcb17cd7d8719,2,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37,ferramentas_jardim
33,00143d0f86d6fbd9f9b38ab440ac16f5,2,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10,esporte_lazer
34,00143d0f86d6fbd9f9b38ab440ac16f5,3,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10,esporte_lazer
43,001ab0a7578dd66cd4b0a71f5b6e1e41,2,0b0172eb0fd18479d29c3bc122c058c2,5656537e588803a555b8eb41f07a944b,2018-01-04 02:33:42,24.89,17.63,eletronicos
44,001ab0a7578dd66cd4b0a71f5b6e1e41,3,0b0172eb0fd18479d29c3bc122c058c2,5656537e588803a555b8eb41f07a944b,2018-01-04 02:33:42,24.89,17.63,eletronicos
...,...,...,...,...,...,...,...,...
112617,ffecd5a79a0084f6a592288c67e3c298,3,50fd2b788dc166edd20512370dac54df,8b321bb669392f5163d04c59e235e066,2018-03-05 20:15:27,21.90,15.79,eletronicos
112635,fff8287bbae429a99bb7e8c21d151c41,2,bee2e070c39f3dd2f6883a17a5f0da45,4e922959ae960d389249c378d1c939f5,2018-03-27 12:29:22,180.00,48.14,informatica_acessorios
112641,fffb9224b6fc7c43ebb0904318b10b5f,2,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19,relogios_presentes
112642,fffb9224b6fc7c43ebb0904318b10b5f,3,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19,relogios_presentes
112643,fffb9224b6fc7c43ebb0904318b10b5f,4,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19,relogios_presentes

In [10]:
df_2 = df_1.loc[df_1.groupby(['order_id', 'product_id'])['order_item_id'].idxmax()]
df_2

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,cool_stuff
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,pet_shop
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,moveis_decoracao
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,perfumaria
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,ferramentas_jardim
...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,utilidades_domesticas
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,informatica_acessorios
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,esporte_lazer
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,informatica_acessorios
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,cama_mesa_banho

In [11]:
df_2['P*Q'] = df_2['order_item_id']  * df_2['price']
df_2.sort_values('P*Q', ascending=False).head(30)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,P*Q
1654,03caa2c082116e1d31e67e9ae3700499,8,5769ef0a239114ac3a854af00df129e4,b37c4c02bda3161a7546a4e6d222d5b2,2017-10-06 15:28:20,1680.00,28.01,telefonia_fixa,13440.00
50771,736e1922ae60d0d6a89247b851902527,4,19936fa4f614ee0590d3b77ac83fd648,b37c4c02bda3161a7546a4e6d222d5b2,2018-07-23 04:31:36,1790.00,28.72,telefonia_fixa,7160.00
3556,0812eb902a67711a1cb742b3cdaa65ae,1,489ae2aa008f021502940f251d4cce7f,e3b4998c7a498169dc7bce44e6bb6277,2017-02-16 20:37:36,6735.00,194.31,utilidades_domesticas,6735.00
112233,fefacc66af859508bf1a7934eab1e97f,1,69c590f7ffc7bf8db97190b6cb6ed62e,80ceebb4ee9b31afb6c6a916a574a1e2,2018-08-02 04:05:13,6729.00,193.21,pcs,6729.00
107841,f5136e38d1a14a4dbd87dff67da82701,1,1bdf5e6731585cf01aa8169c7028d6ad,ee27a8f15b1dded4d213a468ba4eb391,2017-06-15 02:45:17,6499.00,227.66,artes,6499.00
19515,2cc9089445046817a7539d90805e6e5a,6,c183fd5d2abf05873fa6e1014ed9e06c,f08a5b9dd6767129688d001acafc21e5,2017-12-04 12:55:46,989.10,24.49,agro_industria_e_comercio,5934.60
74336,a96610ab360d42a2e5335a3998b4718a,1,a6492cc69376c469ab6f61d8f44de961,59417c56835dd8e2e72f91f809cd4092,2017-04-18 13:25:18,4799.00,151.34,eletroportateis,4799.00
11249,199af31afc78c699f0dbf71fb178d4d4,1,c3ed642d592594bb648ff4a04cee2747,59417c56835dd8e2e72f91f809cd4092,2017-05-09 15:50:15,4690.00,74.34,eletroportateis,4690.00
79473,b4c4b76c642808cbe472a32b86cddc95,2,3db0b74faf0d26a6b252528659d6b849,c4f7fee5b0db50e87766f5a4d1b1b758,2018-07-18 12:25:53,2299.95,104.77,cool_stuff,4599.90
62086,8dbc85d1447242f3b127dda390d56e19,1,259037a6a41845e455183f89c5035f18,c72de06d72748d1a0dfb2125be43ba63,2018-06-28 12:36:36,4590.00,91.78,pcs,4590.00
93049,d2f270487125ddc41fd134c4003ad1d7,2,564a04f027fb97b53ca08464632db860,2bf6a2c1e71bbd29a4ad64e6d3c3629f,2018-06-11 19:50:18,2200.00,22.75,relogios_presentes,4400.00
29193,426a9742b533fc6fed17d1fd6d143d7e,1,a1beef8f3992dbd4cd8726796aa69c53,512d298ac2a96d1931b6bd30aa21f61d,2018-08-16 14:24:28,4399.87,113.45,instrumentos_musicais,4399.87
11917,1b0bc119ea5ac37e73e2275afc7904ee,3,e56f102e763165e7e32d0f9955f8ee4a,0873d9f8f36123f8d910f4760e788cfb,2018-08-20 14:30:22,1390.00,15.09,pcs,4170.00
45843,68101694e5c5dc7330c91e1bbc36214f,1,6cdf8fc1d741c76586d8b6b15e9eef30,ed4acab38528488b65a9a9c603ff024a,2018-04-05 08:27:27,4099.99,75.27,consoles_games,4099.99
78310,b239ca7cd485940b31882363b52e6674,1,dd113cb02b2af9c8e5787e8f1f0722f6,821fb029fc6e495ca4f08a35d51e53a5,2018-08-02 08:15:14,4059.00,104.51,esporte_lazer,4059.00
59137,86c4eab1571921a6a6e248ed312f5a5a,1,6902c1962dd19d540807d0ab8fade5c6,fa1c13f2614d7b5c4749cbc52fecda94,2017-03-23 20:08:04,3999.90,17.01,relogios_presentes,3999.90
56663,80dfedb6d17bf23539beeef3c768f4d7,1,4ca7b91a31637bd24fb8e559d5e015e4,59417c56835dd8e2e72f91f809cd4092,2017-05-05 20:50:13,3999.00,195.76,eletroportateis,3999.00
67456,9a3966c23190dbdbaabed08e8429c006,1,4c50dcc50f1512f46096d6ef0142c4a9,abe021b01ba992245271b9aa422032df,2017-02-18 18:54:15,3980.00,62.74,NaN,3980.00
28884,41b7766bb1df487d17fb9725b78ff509,1,0563d4cc419141eab2e5b438046e844e,039e6ad9dae79614493083e241147386,2018-05-21 18:16:06,3930.00,49.55,ferramentas_jardim,3930.00
69142,9de73f3e6157169ad6c32b9f313c7dcb,1,0eb41884a8773e019708fb8409fd8347,c510bc1718f0f2961eaa42a23330681a,2018-06-13 12:55:49,3899.00,135.44,bebes,3899.00
93516,d3f66901a6743e15f9311547cc623b91,1,1953c4e517bc25739bc4223ede2ff5bc,2bf6a2c1e71bbd29a4ad64e6d3c3629f,2018-03-28 17:48:31,3700.00,92.59,relogios_presentes,3700.00
102349,e85c92ee6a3ba1ef47e41c23286314d9,1,071930404657f7cd416f75bd063a9d4b,403aa86912527d730337ffcb0fb096ab,2017-02-14 10:19:22,3699.99,36.23,informatica_acessorios,3699.99
72452,a53e05ecd2ed1f46a2b8e1f5828be7c6,1,dd113cb02b2af9c8e5787e8f1f0722f6,821fb029fc6e495ca4f08a35d51e53a5,2018-02-01 14:31:30,3690.00,136.80,esporte_lazer,3690.00
77946,b15c7e972c74684414fb2e659fce916a,3,e272c7b6c21c38e8ee510666a28460d4,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-05-17 04:10:25,1199.00,23.14,informatica_acessorios,3597.00
98567,df85c824523500d4066a0dbdb5d95bed,1,5e954c4ed342c50436d25d5f50a34919,585175ec331ea177fa47199e39a6170a,2017-02-25 18:35:38,3549.00,53.47,pcs,3549.00
25648,3a4b013e014723cc38c9faa8ffdc6387,1,34f99d82cfc355d08d8db780d14aa002,a00824eb9093d40e589b940ec45c4eb0,2018-04-16 07:35:20,3399.99,126.47,pcs,3399.99
45208,66b9c991ee308f9342f6a7f63bb68251,2,19936fa4f614ee0590d3b77ac83fd648,b37c4c02bda3161a7546a4e6d222d5b2,2018-02-19 13:32:12,1650.00,29.12,telefonia_fixa,3300.00
89485,cb418bb4b6115438d20b0141ed5bc9e0,2,e74384c9363e768848854356a37c73f4,522620dcb18a6b31cd7bdf73665113a9,2018-06-21 14:20:16,1599.00,29.07,consoles_games,3198.00
107190,f398a143c0fe171d965db2096cf064cf,1,0c104824e973388d487c67a3d346e96d,bede56095ba33c42038fb85f707b8a42,2017-12-21 09:30:27,3124.00,173.40,beleza_saude,3124.00
36878,53c71d3953507c6239ff73917ed358c9,1,17d98fc630d23a628ec1130f8d69d1d2,f9244d45189d3a3605499abddeade7d5,2018-08-13 20:55:31,3109.99,74.35,cool_stuff,3109.99

In [12]:
top5_category = list(df_2.groupby(['product_category_name'])['P*Q'].sum().reset_index().sort_values(by='P*Q', ascending= False).head(5)['product_category_name'])
top5_category

['beleza_saude',
 'relogios_presentes',
 'cama_mesa_banho',
 'esporte_lazer',
 'informatica_acessorios']

In [13]:
df_3 = df_2[df_2['product_category_name'].isin(top5_category)].sort_values(by='P*Q',ascending=False).reset_index(drop=True)
df_3

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,P*Q
0,d2f270487125ddc41fd134c4003ad1d7,2,564a04f027fb97b53ca08464632db860,2bf6a2c1e71bbd29a4ad64e6d3c3629f,2018-06-11 19:50:18,2200.00,22.75,relogios_presentes,4400.00
1,b239ca7cd485940b31882363b52e6674,1,dd113cb02b2af9c8e5787e8f1f0722f6,821fb029fc6e495ca4f08a35d51e53a5,2018-08-02 08:15:14,4059.00,104.51,esporte_lazer,4059.00
2,86c4eab1571921a6a6e248ed312f5a5a,1,6902c1962dd19d540807d0ab8fade5c6,fa1c13f2614d7b5c4749cbc52fecda94,2017-03-23 20:08:04,3999.90,17.01,relogios_presentes,3999.90
3,d3f66901a6743e15f9311547cc623b91,1,1953c4e517bc25739bc4223ede2ff5bc,2bf6a2c1e71bbd29a4ad64e6d3c3629f,2018-03-28 17:48:31,3700.00,92.59,relogios_presentes,3700.00
4,e85c92ee6a3ba1ef47e41c23286314d9,1,071930404657f7cd416f75bd063a9d4b,403aa86912527d730337ffcb0fb096ab,2017-02-14 10:19:22,3699.99,36.23,informatica_acessorios,3699.99
...,...,...,...,...,...,...,...,...,...
39721,e723fd90e2d095c2762e5e800d759bfa,1,99b5175198369d12de8feee13dafac16,08d2d642cf72b622b14dde1d2f5eb2f5,2017-12-01 17:31:28,5.00,15.10,beleza_saude,5.00
39722,44a2fb6a4520b17de57affbab761dfcc,1,da86f3242cb55a55dd9cd7b19d951685,325f3178fb58e2a9778334621eecdbf9,2017-06-05 04:25:29,4.50,7.78,beleza_saude,4.50
39723,c3df9abd148ceaa39d9911b77b041810,1,eee2fb3dceb9ffd8a99dd4bc4b7e860a,36a968b544695394e4e9d7572688598f,2017-11-17 03:26:53,3.90,11.85,informatica_acessorios,3.90
39724,d7c320185a2f9b32f5e2370ff3f8bd64,1,c2fb26742f8484dbfe9a8d70bdc54025,36a968b544695394e4e9d7572688598f,2017-08-14 06:50:10,3.90,15.10,informatica_acessorios,3.90
39725,f1d5c2e6867fa93ceee9ef9b34a53cbf,1,46fce52cef5caa7cc225a5531c946c8b,2d2322d842118867781fc737e96d59a1,2018-08-28 21:30:15,2.20,7.39,beleza_saude,2.20

In [14]:
df_3['product_id'].value_counts().head(20)

product_id
99a4788cb24856965c36a24e339b6058    467
d1c427060a0f73f6b889a5c7c61f2ac4    323
53b36df67ebb7c41585e8d54d6772e08    306
154e7e31ebfa092203795c972e5804a6    269
2b4609f8948be18874494203496bc318    259
3dd2a17168ec895c781a9191c1e95ad7    255
7c1bd920dbdf22470b68bde975dd3ccf    225
e0d64dcfaa3b6db5c54ca298ae101d05    194
bb50f2e236e5eea0100680137654686c    187
a62e25e09e05e6faf31d90c6ec1aa3d1    172
a92930c327948861c015c919a0bcb4a8    158
e53e557d5a159f5aa2c5e995dfdf244b    156
19c91ef95d509ea33eda93495c4d3481    155
6cdd53843498f92890544667809f1595    151
f1c7f353075ce59d8a6f3cf58f419c9c    150
461f43be3bdf8844e65b62d9ac2c7a5a    144
3fbc0ef745950c7932d5f2a446189725    144
7a10781637204d8d10485c71a6108a2e    142
437c05a395e9e47f9762e677a7068ce7    140
e0cf79767c5b016251fe139915c59a26    131
Name: count, dtype: int64

In [23]:
df_3 = df_3.groupby(['product_category_name','product_id','price']).sum().reset_index()
df_3

,product_category_name,product_id,price,order_id,order_item_id,seller_id,shipping_limit_date,freight_value,P*Q
0,beleza_saude,00210e41887c2a8ef9f791ebc780cc36,32.98,2d8e71bf7d31a41d40f122c8173fdf061fd6c29ecb9dd8...,4,e9779976487b77c6d4ac45f75ec7afe9e9779976487b77...,2017-06-08 02:25:252017-05-26 13:06:162017-06-...,38.47,131.92
1,beleza_saude,00210e41887c2a8ef9f791ebc780cc36,33.99,eb24356203f63304c71d81f2c841a02a226975521c585d...,3,e9779976487b77c6d4ac45f75ec7afe9e9779976487b77...,2017-06-08 13:05:152017-06-30 16:30:08,23.37,101.97
2,beleza_saude,0042f1a9a7e0edd1400c6cd0fda065f8,39.90,4ff907acfe03d4b4eccece88f700eb43,2,a5a1bfcf728ab0e19182959cf0771ee4,2018-02-26 23:31:12,7.00,79.80
3,beleza_saude,006619bbed68b000c8ba3f8725d5409e,68.50,66dea50a8b16d9b4dee7af250b4be1a5,1,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,18.36,68.50
4,beleza_saude,00878d953636afec00d3e85d55a12e7f,100.00,ffce8a2dd7579795f5c1cbe2bf23d51d6a7ac200511e30...,11,955fee9216a65b617aa5c0531780ce60955fee9216a65b...,2018-05-09 21:15:182018-05-07 02:52:442018-06-...,241.31,1100.00
...,...,...,...,...,...,...,...,...,...
14946,relogios_presentes,ff80f0538290775336ee74b4997a855c,136.90,70d311beea4bad34a599296c2095e449,1,4869f7a5dfa277a7dca6462dcf3b52b2,2017-10-20 13:14:27,15.71,136.90
14947,relogios_presentes,ffd2365fb8224dc66883df9351d65deb,938.90,5c9b1834dba6a117e9c46ae856be04c9,1,606ce7768feac12c5e8bd58db8b08f0f,2018-05-24 14:17:13,24.45,938.90
14948,relogios_presentes,ffd2365fb8224dc66883df9351d65deb,948.00,72e2c4bbd8ad5d2eec29b795d95afbe2,1,2bf6a2c1e71bbd29a4ad64e6d3c3629f,2018-05-22 15:31:24,58.77,948.00
14949,relogios_presentes,ffd2365fb8224dc66883df9351d65deb,948.90,63f5cc3a2a31c01c270d24d397a54274,1,fa1c13f2614d7b5c4749cbc52fecda94,2018-06-07 07:11:23,13.51,948.90
14950,relogios_presentes,fff515ea94dbf35d54d256b3e39f0fea,818.00,8f0057f230f19e9f7ad1a5566ef6a980,1,93dc87703c046b603023e75222018b45,2018-07-31 11:03:55,20.83,818.00

In [24]:
df_Best_seller_cama_mesa_banho = df_3[df_3['product_id']=='99a4788cb24856965c36a24e339b6058'] # 1 variedade 7
print(df_Best_seller_cama_mesa_banho['P*Q'].sum())
df_Best_seller_informatica_acessorios = df_3[df_3['product_id']=='d1c427060a0f73f6b889a5c7c61f2ac4'] # 2 Variedade 13
print(df_Best_seller_informatica_acessorios['P*Q'].sum())
df_Best_seller_relogios_presentes = df_3[df_3['product_id']=='53b36df67ebb7c41585e8d54d6772e08'] # 3 Variedade 20
print(df_Best_seller_relogios_presentes['P*Q'].sum())

45767.46000000001
47993.47
38317.219999999994

In [26]:
df_Best_seller_cama_mesa_banho

,product_category_name,product_id,price,order_id,order_item_id,seller_id,shipping_limit_date,freight_value,P*Q
5529,cama_mesa_banho,99a4788cb24856965c36a24e339b6058,74.00,5139f51749d25619bb9e6153e11a18aa16a811fb1fdf86...,10,4a3ca9315b744ce9f8e93743614938844a3ca9315b744c...,2018-08-16 04:45:092018-08-02 19:31:212018-08-...,158.94,740.00
5530,cama_mesa_banho,99a4788cb24856965c36a24e339b6058,79.90,e2047aaabab2869c1080a51c3e6b64ce1aa9e8f35ac38d...,38,4a3ca9315b744ce9f8e93743614938844a3ca9315b744c...,2018-06-12 15:10:332018-06-13 19:01:162018-06-...,648.38,3036.20
5531,cama_mesa_banho,99a4788cb24856965c36a24e339b6058,83.79,df93ef458b1b9c8a6776d6ffec19af83e1860ce96baa10...,4,53d00c40e32aeb924a84ce72b1af869d53d00c40e32aeb...,2018-05-07 02:53:072018-05-08 18:31:452018-05-...,31.96,335.16
5532,cama_mesa_banho,99a4788cb24856965c36a24e339b6058,84.00,8309d4331303ee734179e1c7da304fe86275a054b07c80...,16,4a3ca9315b744ce9f8e93743614938844a3ca9315b744c...,2018-05-09 14:54:492018-05-15 17:55:172018-05-...,268.02,1344.00
5533,cama_mesa_banho,99a4788cb24856965c36a24e339b6058,86.00,0504c112cd5ef9650a65748c4dc380cbff79282c8f4c58...,2,53d00c40e32aeb924a84ce72b1af869d53d00c40e32aeb...,2018-04-23 09:31:162018-04-25 12:53:28,30.13,172.00
5534,cama_mesa_banho,99a4788cb24856965c36a24e339b6058,86.90,368b20312c68710e9d75cbb5cef5c469a8eeef949a9736...,75,4a3ca9315b744ce9f8e93743614938844a3ca9315b744c...,2018-01-07 23:36:562018-02-09 18:15:472018-01-...,1363.14,6517.50
5535,cama_mesa_banho,99a4788cb24856965c36a24e339b6058,89.90,f726f658e548a5e6e7f2c8f4ee47d73ff142ccab4f2274...,374,4a3ca9315b744ce9f8e93743614938844a3ca9315b744c...,2017-03-23 09:05:502017-11-29 20:55:392017-06-...,5189.45,33622.60

In [27]:
df_Best_seller_informatica_acessorios

,product_category_name,product_id,price,order_id,order_item_id,seller_id,shipping_limit_date,freight_value,P*Q
12404,informatica_acessorios,d1c427060a0f73f6b889a5c7c61f2ac4,109.99,b2c7ce470c3bc3cebaef61950a33f2f87d48e6b043ed5d...,15,a1043bafd471dff536d0c462352beb48a1043bafd471df...,2018-06-14 09:01:382018-06-14 11:00:042018-06-...,821.68,1649.85
12405,informatica_acessorios,d1c427060a0f73f6b889a5c7c61f2ac4,119.00,c78ebbd697d902b76f0b9381f22b17cddf82ea7ca7f0f7...,79,a1043bafd471dff536d0c462352beb48a1043bafd471df...,2018-04-23 20:35:192018-05-16 11:58:122018-05-...,2376.86,9401.00
12406,informatica_acessorios,d1c427060a0f73f6b889a5c7c61f2ac4,119.99,2bec039adcca39ad3a2d76a949e6c99dd8eaec04332d52...,28,a1043bafd471dff536d0c462352beb48a1043bafd471df...,2018-07-31 13:04:272018-06-26 02:58:292018-07-...,1155.96,3359.72
12407,informatica_acessorios,d1c427060a0f73f6b889a5c7c61f2ac4,129.00,0517ba063462fdd36525fd7e9ef72cee1bd87f39c9bb8c...,20,a1043bafd471dff536d0c462352beb48a1043bafd471df...,2018-03-21 00:10:592018-03-27 09:48:042018-03-...,953.57,2580.00
12408,informatica_acessorios,d1c427060a0f73f6b889a5c7c61f2ac4,129.99,d8d0488eb1aa33a391551c5bbe00e93f3462b9aa946649...,2,a1043bafd471dff536d0c462352beb48a1043bafd471df...,2017-05-03 02:25:172017-05-05 20:45:10,75.69,259.98
12409,informatica_acessorios,d1c427060a0f73f6b889a5c7c61f2ac4,139.00,ebd182d678f7c5aec1f89d5f6f9848eca1fb0092d4374d...,22,a1043bafd471dff536d0c462352beb48a1043bafd471df...,2018-03-29 02:28:362018-03-26 11:08:072018-03-...,959.04,3058.00
12410,informatica_acessorios,d1c427060a0f73f6b889a5c7c61f2ac4,139.99,7114c189256c666ea43b7230a66ff2a71f90220e4ad979...,13,a1043bafd471dff536d0c462352beb48a1043bafd471df...,2017-08-02 10:55:252017-07-10 03:50:212017-04-...,504.97,1819.87
12411,informatica_acessorios,d1c427060a0f73f6b889a5c7c61f2ac4,149.00,80b8546dc40a96e03d6be3b166ceb0254cc9bc748dac6b...,71,a1043bafd471dff536d0c462352beb48a1043bafd471df...,2018-01-26 13:48:542018-02-16 12:28:192018-02-...,2511.95,10579.00
12412,informatica_acessorios,d1c427060a0f73f6b889a5c7c61f2ac4,149.99,848b0561d4bc26f57b288a5004f38683339c4a8fdff279...,67,a1043bafd471dff536d0c462352beb48a1043bafd471df...,2017-12-01 19:19:022017-11-17 03:10:272017-11-...,2594.86,10049.33
12413,informatica_acessorios,d1c427060a0f73f6b889a5c7c61f2ac4,159.00,4b8554eedaef8a794db32fd6f2663cc0e550243ca45f5d...,3,a1043bafd471dff536d0c462352beb48a1043bafd471df...,2018-01-18 17:15:262018-01-22 14:30:242018-01-...,88.26,477.00
12414,informatica_acessorios,d1c427060a0f73f6b889a5c7c61f2ac4,159.99,cd2d1270c05b7eea6c1be319b78ce73f28c80a03a80d51...,15,a1043bafd471dff536d0c462352beb48a1043bafd471df...,2017-09-14 17:15:152017-04-04 02:31:202017-02-...,510.66,2399.85
12415,informatica_acessorios,d1c427060a0f73f6b889a5c7c61f2ac4,179.99,c2a74c32297a978e0e9b2b2797b917eb11c177c8e97725...,11,a1043bafd471dff536d0c462352beb48a1043bafd471df...,2018-01-12 21:08:442018-01-12 21:36:212018-01-...,319.77,1979.89
12416,informatica_acessorios,d1c427060a0f73f6b889a5c7c61f2ac4,189.99,4aa0af6a36b380f42a173210f1d15a1e562e2ed068c6e2...,2,a1043bafd471dff536d0c462352beb48a1043bafd471df...,2017-10-25 16:35:332017-10-25 03:12:44,86.07,379.98

In [28]:
df_Best_seller_relogios_presentes

,product_category_name,product_id,price,order_id,order_item_id,seller_id,shipping_limit_date,freight_value,P*Q
13576,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,99.90,84f89b4f4b956843277c6b990bd06b2f4296bf3920be4e...,120,7d13fca15225358621be4086e1eb09647d13fca1522535...,2018-05-01 23:35:092018-05-14 20:55:002018-05-...,0.00,11988.00
13577,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,106.90,0a0e91f265e0c09af322a473351b61d118a00857887339...,15,4869f7a5dfa277a7dca6462dcf3b52b24869f7a5dfa277...,2018-04-26 19:31:332018-04-25 21:30:342018-04-...,0.00,1603.50
13578,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,109.99,152e3e1d1cd5a952b1f4049ff29ab695,1,7d13fca15225358621be4086e1eb0964,2018-05-02 08:51:56,0.00,109.99
13579,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,110.00,b05ccefa0dbc75b1e0307c4da1cdb77238b6f49502e649...,37,7d13fca15225358621be4086e1eb09647d13fca1522535...,2018-04-26 09:15:242018-04-26 11:55:242018-04-...,120.37,4070.00
13580,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,112.00,b89d417b1ba9f8e416b9e333ffa01a930a998b0552bd0e...,2,7d13fca15225358621be4086e1eb09647d13fca1522535...,2018-08-06 10:25:112018-08-08 19:15:21,26.88,224.00
13581,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,112.90,ffe73fc1d73e03fdb50e63903ddfe8822f2bc2963a4012...,8,4869f7a5dfa277a7dca6462dcf3b52b24869f7a5dfa277...,2018-04-23 13:15:152018-04-23 23:35:142018-04-...,76.01,903.20
13582,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,115.00,4a6779a79e8397160e34e7e005321200c237167dd6b573...,30,7d13fca15225358621be4086e1eb09647d13fca1522535...,2018-05-17 16:18:402018-05-17 20:57:052018-03-...,361.29,3450.00
13583,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,116.90,21dc00cebbf91043aad476465c49c42f72520be5b5b4c3...,7,4869f7a5dfa277a7dca6462dcf3b52b24869f7a5dfa277...,2018-05-21 13:19:302018-05-21 15:35:212018-05-...,2.77,818.30
13584,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,117.90,385a6cde4031f6d16c0c80c96c7025800c7207c23f4eb8...,4,4869f7a5dfa277a7dca6462dcf3b52b24869f7a5dfa277...,2018-05-04 19:55:202018-04-30 14:31:552018-05-...,14.87,471.60
13585,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,119.00,1397417a57ad1bbfe8d639df8cdee9088135d95a571b0c...,20,7d13fca15225358621be4086e1eb09647d13fca1522535...,2018-07-06 18:31:032018-07-02 15:57:542018-06-...,329.70,2380.00
13586,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,120.00,e88333581538e25e87d48b2dbc1782b8a4e4558822ee82...,6,4869f7a5dfa277a7dca6462dcf3b52b24869f7a5dfa277...,2018-03-20 09:35:322018-03-16 17:09:592018-03-...,134.32,720.00
13587,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,125.00,c10600160de02ce63a426cc0e410e7a74c7e0a5ac91085...,3,7d13fca15225358621be4086e1eb09647d13fca1522535...,2018-02-28 22:30:392018-03-12 03:49:072018-03-...,42.05,375.00
13588,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,128.89,049c844d7707d97ba1600196919474f4bc8040ec215e52...,7,7d13fca15225358621be4086e1eb09647d13fca1522535...,2018-03-05 16:35:432018-03-07 21:09:352018-03-...,106.30,902.23
13589,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,133.00,d55cd104a6a05987a3b55d39c0e7799551ee2d580bfba3...,15,4869f7a5dfa277a7dca6462dcf3b52b24869f7a5dfa277...,2017-12-05 18:49:142017-12-04 21:59:292017-12-...,277.33,1995.00
13590,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,134.90,356f68057b81e3a00ee64a8e160515178866f85227409d...,8,4869f7a5dfa277a7dca6462dcf3b52b24869f7a5dfa277...,2017-10-09 13:28:162017-09-29 05:55:112017-09-...,98.48,1079.20
13591,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,138.00,d27c9535dfd56cfe107bc9eac1ac3e316bdee91009b22f...,3,4869f7a5dfa277a7dca6462dcf3b52b24869f7a5dfa277...,2017-09-21 19:03:272017-09-25 15:15:212017-09-...,43.91,414.00
13592,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,149.00,fb0c01b2efee313f5231a89c4a55e498a31768d1614db2...,4,4869f7a5dfa277a7dca6462dcf3b52b24869f7a5dfa277...,2017-12-07 10:57:092017-12-07 21:37:312017-12-...,76.40,596.00
13593,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,159.90,ca3e4f02c7e6d10a27225305edaee9dac339883c001902...,18,4869f7a5dfa277a7dca6462dcf3b52b24869f7a5dfa277...,2017-08-02 10:35:172017-08-03 17:23:162017-08-...,256.13,2878.20
13594,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,163.00,9b7cadbb92caa7ecc994bc25a7932963b2f6d9c004d4df...,10,4869f7a5dfa277a7dca6462dcf3b52b24869f7a5dfa277...,2017-07-24 03:33:502017-07-31 11:03:292017-08-...,156.43,1630.00
13595,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,169.90,fb8e4428d340ab5bfa482ef6fc97efbc63576020815760...,9,4869f7a5dfa277a7dca6462dcf3b52b24869f7a5dfa277...,2017-09-08 08:44:162017-09-08 18:35:292017-09-...,63.08,1529.10
13596,relogios_presentes,53b36df67ebb7c41585e8d54d6772e08,179.90,ba6ceea3a35916e51113b91f726b1f89,1,4869f7a5dfa277a7dca6462dcf3b52b2,2017-09-18 11:44:07,16.01,179.90

In [17]:
df_Best_seller_cama_mesa_banho = df_3[df_3['product_id']=='99a4788cb24856965c36a24e339b6058'] # 1 variedade 7
print(df_Best_seller_cama_mesa_banho['P*Q'].sum())
df_Best_seller_informatica_acessorios = df_3[df_3['product_id']=='d1c427060a0f73f6b889a5c7c61f2ac4'] # 2 Variedade 13
print(df_Best_seller_informatica_acessorios['P*Q'].sum())
df_Best_seller_relogios_presentes = df_3[df_3['product_id']=='53b36df67ebb7c41585e8d54d6772e08'] # 3 Variedade 20
print(df_Best_seller_relogios_presentes['P*Q'].sum())

45767.46000000001
47993.47
38317.22

### TESTE

In [100]:
df_3[df_3['product_id']=='99a4788cb24856965c36a24e339b6058']['price'].unique()

array([89.9 , 79.9 , 86.9 , 74.  , 86.  , 84.  , 83.79])

In [ ]:
# df_2 = (df_1.groupby(['product_category_name', 'product_id']).size().reset_index(name='qtd'))
# df_2

,product_category_name,product_id,price,qtd
0,agro_industria_e_comercio,018ca97302e4293050cc41413194bb19,88.00,1
1,agro_industria_e_comercio,026f43af35e7951067097527d5c31bcc,179.90,2
2,agro_industria_e_comercio,07f01b6fcacc1b187a71e5074199db2d,57.00,1
3,agro_industria_e_comercio,0a0adf0de1769b2970f3096d0b5abfb7,58.50,1
4,agro_industria_e_comercio,0a27862bbf658a5b8cf655761bc5c72d,51.73,1
...,...,...,...,...
41707,utilidades_domesticas,ffaaddefb271481c66d4bd79844ecdae,13.31,3
41708,utilidades_domesticas,ffbc83054b3741a8d67fc59d9cf9d42d,44.90,1
41709,utilidades_domesticas,ffc88104d219c1b767d566fd93653dd2,39.90,1
41710,utilidades_domesticas,ffe0fc4e02c3559643ac063fa5cf9d07,54.75,1
41711,utilidades_domesticas,ffe0fc4e02c3559643ac063fa5cf9d07,56.25,1

In [ ]:
# df_3 = df_2.sort_values(['product_category_name', 'qtd'],ascending=[True, False])
# df_3

           product_category_name                        product_id  qtd
7      agro_industria_e_comercio  11250b0d4b709fee92441c5f34122aed   22
24     agro_industria_e_comercio  423a6644f0aa529e8828ff1f91003690   18
35     agro_industria_e_comercio  672e757f331900b9deea127a2a7b79fd   17
22     agro_industria_e_comercio  3bebad3cf2c8d1a8d3ce97174643e054   14
40     agro_industria_e_comercio  a0fe1efb855f3e786f0650268cd77f44   13
...                          ...                               ...  ...
32332      utilidades_domesticas  ff25a6dd5b0db59bf1f8977c272270d0    1
32334      utilidades_domesticas  ff5bdcc63751127e726cb69cff0cb5de    1
32335      utilidades_domesticas  ff85ff517698c3fe8b200afddda7fb3a    1
32338      utilidades_domesticas  ffbc83054b3741a8d67fc59d9cf9d42d    1
32339      utilidades_domesticas  ffc88104d219c1b767d566fd93653dd2    1

[32341 rows x 3 columns]

In [ ]:
# df_best_seller_cat = df_1[df_1['product_id'].isin(df_3['product_id'])]
# df_best_seller_cat['P * Q'] =  df_1

# #df_best_seller_cat = df_best_seller_cat.groupby(['product_category_name','product_id', 'price']).count().reset_index()
# df_best_seller_cat

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,cool_stuff
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,pet_shop
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,moveis_decoracao
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,perfumaria
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,ferramentas_jardim
...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,utilidades_domesticas
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,informatica_acessorios
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,esporte_lazer
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,informatica_acessorios
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,cama_mesa_banho

In [ ]:
# df_best_seller_cat['sum_categoria'] = df_best_seller_cat.groupby('product_category_name')['order_id'].transform('sum')
# df_best_seller_cat.sort_values(by='sum_categoria',ascending=False,inplace=True) 
# df_best_seller_cat

,product_category_name,product_id,price,order_id,order_item_id,seller_id,shipping_limit_date,freight_value,sum_categoria
199,moveis_decoracao,aca2eb7d00ea1a7b8ebd4e68314663af,109.90,2,2,2,2,2,527
198,moveis_decoracao,aca2eb7d00ea1a7b8ebd4e68314663af,89.90,5,5,5,5,5,527
197,moveis_decoracao,aca2eb7d00ea1a7b8ebd4e68314663af,75.00,116,116,116,116,116,527
196,moveis_decoracao,aca2eb7d00ea1a7b8ebd4e68314663af,69.90,404,404,404,404,404,527
66,cama_mesa_banho,99a4788cb24856965c36a24e339b6058,79.90,35,35,35,35,35,488
...,...,...,...,...,...,...,...,...,...
172,la_cuisine,33900d427fa4bd3f509cdacda72e84a3,140.00,2,2,2,2,2,3
134,fashion_roupa_infanto_juvenil,57bdf3098169cccdb62221bd3e089cbd,39.99,3,3,3,3,3,3
171,la_cuisine,33900d427fa4bd3f509cdacda72e84a3,116.00,1,1,1,1,1,3
240,portateis_cozinha_e_preparadores_de_alimentos,7afdd65f79f63819ff5bee328843fa37,21.52,3,3,3,3,3,3
262,seguros_e_servicos,6c7a0a349ad11817745e3ad58abd5c79,183.29,1,1,1,1,1,1

In [ ]:
# df_best_seller_cat['product_category_name'].value_counts()

product_category_name
relogios_presentes                               21
informatica_acessorios                           13
artes                                            12
bebes                                            12
audio                                            11
                                                 ..
dvds_blu_ray                                      1
musica                                            1
fashion_roupa_infanto_juvenil                     1
portateis_cozinha_e_preparadores_de_alimentos     1
seguros_e_servicos                                1
Name: count, Length: 73, dtype: int64